-
  name: Install Docker CentOS
  hosts: kube_nodes
  tasks:
    - name: Install required packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
    - name: Add docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
    - name: Install Docker components new
      yum:
        name:
          - docker-ce-18.06.3.ce-3.el7
          - containerd.io
        state: present
    - name: Start and enable docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: Add osboxes user to docker group
      user:
        name: osboxes
        groups: docker
        append: yes
