-
  name: Provision Kubernetes linux_nodes
  hosts: kube_nodes
  tasks:
    - name: turn off swap
      command: swapoff -a
    - name: comment swap in fstab
      replace:
        path: /etc/fstab
        regexp: '^UUID(.*swap.*)'
        replace: '#UUID\1'
    - name: Copy repo file from ansible controller
      copy:
        src: /home/osboxes/ansible/provision-docker-kubernetes/source/kubernetes.repo
        dest: /etc/yum.repos.d/kubernetes.repo
        owner: root
        group: root
        mode: 0644
    - name: Set SELinux in permissive mode
      command: setenforce 0
    - name: Set SELinux in permissive mode in config file
      replace:
        path: /etc/selinux/config
        regexp: '^SELINUX=enforcing$'
        replace: 'SELINUX=permissive'
    - name: Install a list of kuberetes packages
      yum:
        name:
         - kubelet
         - kubeadm
         - kubectl
        enablerepo: kubernetes
        disable_excludes: kubernetes
        state: present
    - name: Start and enable kubelet service
      service:
        name: kubelet
        state: started
        enabled: yes
    - name: Copy k8s.conf file from ansible controller
      copy:
        src: /home/osboxes/ansible/provision-docker-kubernetes/source/k8s.conf
        dest: /etc/sysctl.d/k8s.conf
        owner: root
        group: root
        mode: 0644
    - name: read values from all system directories
      command: sysctl --system
    - name: Add the br_netfilter
      modprobe:
        name: br_netfilter
        state: present
